spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://127.0.0.1:3306/spring_batch?characterEncoding=UTF-8&serverTimezone-UTC
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: 1234
batch:
  initialize-scheme: never